/**
 * Bark Technologies — Seed Data
 * Real product data extracted from information/barktechnologies_information_sources/
 */

export const seedData = {
  categories: [
    { name: 'Die Cutting & Creasing', slug: 'die-cutting', description: 'Die cutting and creasing machines for corrugated board and card stock', sortOrder: 1, isActive: true },
    { name: 'Flute Laminating', slug: 'laminating', description: 'Flute laminator and film lamination machines for cardboard lamination', sortOrder: 2, isActive: true },
    { name: 'Window Patching', slug: 'window-patching', description: 'Window patching machines for packaging boxes', sortOrder: 3, isActive: true },
    { name: 'Printing', slug: 'printing', description: 'Rotary printing machines for corrugated boxes', sortOrder: 4, isActive: true },
    { name: 'Cutting', slug: 'cutting', description: 'NC cutter machines for precision cutting', sortOrder: 5, isActive: true },
    { name: 'Corrugating', slug: 'corrugating', description: 'Single facer machines for corrugated cardboard production', sortOrder: 6, isActive: true },
    { name: 'Material Handling', slug: 'material-handling', description: 'Mill roll stands for paper roll handling', sortOrder: 7, isActive: true },
    { name: 'Stitching', slug: 'stitching', description: 'Stitching machines for binding boxes', sortOrder: 8, isActive: true },
    { name: 'Creasing Matrix', slug: 'creasing-matrix', description: 'Creasing matrix cutter and accessories', sortOrder: 9, isActive: true },
    { name: 'Folder Gluing', slug: 'folder-gluing', description: 'Folder gluer machines for corrugated box folding and gluing', sortOrder: 10, isActive: true },
    { name: 'Pasting', slug: 'pasting', description: 'Flyer pasting and sheet pasting machines', sortOrder: 11, isActive: true },
  ],

  products: [
    {
      name: 'Automatic Die Cutting And Creasing Machine',
      slug: 'automatic-die-cutting-and-creasing-machine',
      categorySlug: 'die-cutting',
      description: 'Automatic Die Cutting And Creasing Machine, fitted with creasing dies and side wheel adjustment for increasing and decreasing the height as per requirement. Special equipment for die-cutting of advanced coloured boxes made of paper and paper board. Tested on various industry norms for performance and sturdy construction.',
      shortDescription: 'Special equipment for die-cutting of advanced coloured boxes made of paper and paper board.',
      specs: [
        { key: 'Model', value: 'MY-1500A' },
        { key: 'Warranty', value: '1 Year' },
        { key: 'Delivery Time', value: '50 to 60 Days' },
        { key: 'Max. Paper Size', value: '1500x1105mm' },
        { key: 'Min. Paper Size', value: '500x420mm' },
        { key: 'Max. Cutting Size', value: '1480x1090mm' },
        { key: 'Max. Pressure', value: '350 Tons' },
        { key: 'Sheet Thickness', value: 'Cardboard 250-2500g/m2, Corrugated Board < 8mm' },
        { key: 'Max. Cutting Speed', value: '5000 sheets/h' },
        { key: 'Die-Cutting Precision', value: '±0.18mm' },
        { key: 'Min. Gripper Edge', value: '8mm' },
        { key: 'Max. Feeding Pile Height', value: '1650mm' },
        { key: 'Max. Delivery Pile Height', value: '1500mm' },
        { key: 'Total Power', value: '20 KW' },
        { key: 'Weight', value: '20 Tons' },
        { key: 'Overall Dimension', value: '7900x4600x2600mm' },
      ],
      media: [{ type: 'image', url: '/images/product/automatic-die-cutting-and-creasing.png', alt: 'Automatic Die Cutting And Creasing Machine', sortOrder: 1 }],
      isActive: true,
      isFeatured: true,
      seoTitle: 'Automatic Die Cutting And Creasing Machine | Bark Technologies',
      seoDescription: 'High-performance automatic die cutting and creasing machine for corrugated board and card stock. 350 Tons pressure, 5000 sheets/hour.',
    },
    {
      name: 'High Speed Automatic Die Cutting & Creasing Machine',
      slug: 'high-speed-automatic-die-cutting-and-creasing-machine',
      categorySlug: 'die-cutting',
      description: 'High Speed Automatic Die Cutting & Creasing Machine fitted with creasing dies and side wheel adjustment. Special equipment for die-cutting of advanced coloured boxes made of paper and paper board. Available in two model variants (MY-880FAST / MY-1050FAST) with cutting speeds up to 10000 sheets/hour.',
      shortDescription: 'High-speed die cutting machine with up to 10000 sheets/hour cutting speed.',
      specs: [
        { key: 'Model', value: 'MY-1050FAST | MY-880FAST' },
        { key: 'Warranty', value: '1 Year' },
        { key: 'Delivery Time', value: '50 to 60 Days' },
        { key: 'Max. Paper Size', value: '1060x760mm | 880x610mm' },
        { key: 'Min. Paper Size', value: '380x340mm | 320x240mm' },
        { key: 'Max. Cutting Size', value: '1040x750mm | 860x590mm' },
        { key: 'Max. Die Cutting Speed', value: '10000 s/h | 10000 s/h' },
        { key: 'Sheet Thickness', value: 'Corrugated board ≤4mm, Cardboard 0.1-4mm | 0.1-4mm' },
        { key: 'Die Cutting Accuracy', value: '±0.1mm | ±0.1mm' },
        { key: 'Min. Gripper Edge', value: '7mm | 7mm' },
        { key: 'Max. Feeding Pile', value: '1600mm | 1400mm' },
        { key: 'Max. Delivery Pile', value: '1400mm | 1100mm' },
        { key: 'Max. Pressure', value: '350 Tons | 250 Tons' },
        { key: 'Total Power', value: '21 KW | 15 KW' },
        { key: 'Net Weight', value: '17 Tons | 13 T' },
        { key: 'Air Requirement', value: '0.8Mpa, >0.36m3/min' },
      ],
      media: [{ type: 'image', url: '/images/product/High-Speed-Automatic-Die-Cutting-and-creasing-machine.png', alt: 'High Speed Automatic Die Cutting Machine', sortOrder: 1 }],
      isActive: true,
      isFeatured: true,
      seoTitle: 'High Speed Automatic Die Cutting Machine | Bark Technologies',
      seoDescription: 'High-speed die cutting machine up to 10000 sheets/hour with ±0.1mm accuracy.',
    },
    {
      name: 'Semi Automatic Die Cutting and Creasing Machine',
      slug: 'semi-automatic-die-cutting-and-creasing-machine',
      categorySlug: 'die-cutting',
      description: 'Semi Automatic Die Cutting and Creasing Machine is a professional equipment for die cutting of high end colorful boxes. Adopts advanced high intensity gripper bars for processing various paper board, cardboard and corrugated board. Equipped with high precision intermittent mechanism, flexible pneumatic clutch, pneumatic locking device, programmable controller and HMI display. Available in three model variants (BMY1300/1500/1680).',
      shortDescription: 'Professional die cutting machine with programmable controller and HMI interface.',
      specs: [
        { key: 'Model', value: 'BMY1300 | BMY1500 | BMY1680' },
        { key: 'Warranty', value: '1 Year' },
        { key: 'Delivery Time', value: '40 to 45 Days' },
        { key: 'Max. Paper Size', value: '1500x1105mm' },
        { key: 'Min. Paper Size', value: '500x420mm' },
        { key: 'Max. Cutting Size', value: '1480x1090mm' },
        { key: 'Max. Pressure', value: '350 Tons' },
        { key: 'Sheet Thickness', value: 'Cardboard 250-2500g/m2, Corrugated Board < 8mm' },
        { key: 'Max. Cutting Speed', value: '5000 sheets/h' },
        { key: 'Die-Cutting Precision', value: '±0.18mm' },
        { key: 'Min. Gripper Edge', value: '8mm' },
        { key: 'Total Power', value: '20 KW' },
        { key: 'Weight', value: '20 Tons' },
        { key: 'Overall Dimension', value: '7900x4600x2600mm' },
      ],
      media: [{ type: 'image', url: '/images/product/Semi-Automatic-Die-Cutting-&-Creasing-Machine.png', alt: 'Semi Automatic Die Cutting Machine', sortOrder: 1 }],
      isActive: true,
      isFeatured: false,
      seoTitle: 'Semi Automatic Die Cutting Machine | Bark Technologies',
      seoDescription: 'Semi-automatic die cutting machine with programmable controller and HMI.',
    },
    {
      name: 'Automatic Flute Laminator Machine',
      slug: 'automatic-flute-laminator-machine',
      categorySlug: 'laminating',
      description: 'Automatic Flute Laminator Machine for lamination of cardboard to cardboard or cardboard to corrugated paperboard. Designed with auto suction feeding system. Available in two model variants (FMZ-1450H / FMZ-1600H) with speeds up to 9000 pcs/h.',
      shortDescription: 'Automatic flute laminator for cardboard and corrugated paperboard lamination.',
      specs: [
        { key: 'Model', value: 'FMZ-1450H | FMZ-1600H' },
        { key: 'Warranty', value: '1 Year' },
        { key: 'Delivery Time', value: '35 to 40 Days' },
        { key: 'Max size of cover face', value: '1450x1400mm | 1600x1450mm' },
        { key: 'Min size of cover face', value: '400x400mm | 360x360mm' },
        { key: 'Top paper thickness', value: '120-600g | 120-600g' },
        { key: 'Bottom sheet thickness', value: '2/4 ply A/B/C/E/F Flute, ≤8mm' },
        { key: 'Max. Machine speed', value: '9000 pcs/h, 150 m/min' },
        { key: 'Precision', value: '±1mm | ±1mm' },
        { key: 'Power', value: '15 kW | 16 kW' },
        { key: 'Size', value: '14.1m x 2.41m x 2.68m | 15.6m x 2.61m x 2.68m' },
        { key: 'Weight', value: 'About 7 Tons | About 7.5 Tons' },
      ],
      media: [{ type: 'image', url: '/images/product/high-speed-automatic-flute-laminator.png', alt: 'Automatic Flute Laminator Machine', sortOrder: 1 }],
      isActive: true,
      isFeatured: true,
      seoTitle: 'Automatic Flute Laminator Machine | Bark Technologies',
      seoDescription: 'Automatic flute laminator with 9000 pcs/h speed for cardboard and corrugated board.',
    },
    {
      name: 'High Speed Automatic Flute Laminator Machine',
      slug: 'high-speed-automatic-flute-laminator-machine',
      categorySlug: 'laminating',
      description: 'Automatic High Speed Flute Laminator Machine with auto suction feeding system. Available in two model variants (FMZ-1450H / FMZ-1700H) with speeds up to 15000 pcs/h. Ideal for high-end packaging box production.',
      shortDescription: 'High-speed flute laminator with up to 15000 pcs/h speed.',
      specs: [
        { key: 'Model', value: 'FMZ-1450H | FMZ-1700H' },
        { key: 'Warranty', value: '1 Year' },
        { key: 'Max size of cover face', value: '1450x1450mm | 1650x1650mm' },
        { key: 'Min size of cover face', value: '400x360mm | 400x360mm' },
        { key: 'Top paper thickness', value: '120-600g | 120-600g' },
        { key: 'Bottom sheet thickness', value: '0.5-10mm (B, A, AB, E, G flute)' },
        { key: 'Max. Machine speed', value: '15000 pcs/h, 150 m/min' },
        { key: 'Lamination Accuracy', value: '±1.5mm | ±1.5mm' },
        { key: 'Power', value: '22 kW | 25 kW' },
        { key: 'Dimension L*W*H', value: '14232x2400x2571mm | 14735x2750x2571mm' },
        { key: 'Weight', value: 'About 7.7 Tons | About 8 Tons' },
        { key: 'Height of Bottom Paper', value: '400mm | 400mm' },
        { key: 'Height of Top Paper', value: '1800mm | 1800mm' },
      ],
      media: [{ type: 'image', url: '/images/product/high-speed-automatic-flute-laminator.png', alt: 'High Speed Automatic Flute Laminator', sortOrder: 1 }],
      isActive: true,
      isFeatured: true,
      seoTitle: 'High Speed Automatic Flute Laminator | Bark Technologies',
      seoDescription: 'High-speed flute laminator with 15000 pcs/h speed for high-end packaging boxes.',
    },
    {
      name: 'High Speed Automatic Flute Laminator',
      slug: 'high-speed-automatic-flute-laminator',
      categorySlug: 'laminating',
      description: 'High Speed Automatic Flute Laminator with auto suction feeding system for both top linerboards and bottom corrugated boards. Available in two model variants (FMZ-1450H / FMZ-1700H) with speeds up to 12000 pcs/h. Ideal for high-end packaging boxes.',
      shortDescription: 'Automatic flute laminator with 12000 pcs/h speed and auto suction feeding.',
      specs: [
        { key: 'Model', value: 'FMZ-1450H | FMZ-1700H' },
        { key: 'Warranty', value: '1 Year' },
        { key: 'Max size of cover face', value: '1450x1400mm | 1600x1450mm' },
        { key: 'Min size of cover face', value: '400x400mm | 360x360mm' },
        { key: 'Top paper thickness', value: '100-550g | 100-550g' },
        { key: 'Bottom sheet thickness', value: '2/4 ply A/B/C/E/F Flute, ≤8mm' },
        { key: 'Max. Machine speed', value: '12000 pcs/h, 180 m/min' },
        { key: 'Precision', value: '±1mm | ±1mm' },
        { key: 'Power', value: '15 kW | 16 kW' },
        { key: 'Size', value: '14.1m x 2.41m x 2.68m | 15.6m x 2.61m x 2.68m' },
        { key: 'Weight', value: 'About 7 Tons | About 7.5 Tons' },
      ],
      media: [{ type: 'image', url: '/images/product/high-speed-automatic-flute-laminator.png', alt: 'High Speed Automatic Flute Laminator', sortOrder: 1 }],
      isActive: true,
      isFeatured: false,
      seoTitle: 'High Speed Automatic Flute Laminator | Bark Technologies',
      seoDescription: 'High-speed flute laminator with auto suction feeding for high-end packaging.',
    },
    {
      name: 'Semi Automatic Flute Laminator Machine',
      slug: 'semi-automatic-flute-laminator-machine',
      categorySlug: 'laminating',
      description: 'Semi Automatic Flute Laminator Machine manufactured strictly as per client specifications. Suitable for lamination of top paperboard to bottom paperboard above 350g/m2 or 2 ply board of A/B/C/E/F flute to form a corrugated cardboard. Features automatic feeding for bottom sheet and manual top sheet. Four model variants available (YB-1300A-II / 1450A-II / 1550A-II / 1650A-I).',
      shortDescription: 'Semi-automatic flute laminator with automatic bottom sheet feeding.',
      specs: [
        { key: 'Model', value: 'YB-1300A-II | YB-1450A-II | YB-1550A-II | YB-1650A-I' },
        { key: 'Warranty', value: '1 Year' },
        { key: 'Max size of laminating', value: '1300x1250mm | 1400x1250mm | 1500x1250mm | 1600x1250mm' },
        { key: 'Min size of laminating', value: '360x360mm' },
        { key: 'Top paper thickness', value: '140-800g' },
        { key: 'Bottom sheet thickness', value: '2/4 ply A/B/C/E/F Flute' },
        { key: 'Economic speed', value: '0-100 Piece/min' },
        { key: 'Laminating precision', value: '±1mm' },
        { key: 'Power', value: '7 KW | 7.5 KW | 7.5 KW | 7.5 KW' },
        { key: 'Weight', value: 'About 3.5 t | About 4 t | About 4 t | About 4 t' },
      ],
      media: [{ type: 'image', url: '/images/product/semi-automatic-flute-laminator.png', alt: 'Semi Automatic Flute Laminator', sortOrder: 1 }],
      isActive: true,
      isFeatured: false,
      seoTitle: 'Semi Automatic Flute Laminator | Bark Technologies',
      seoDescription: 'Semi-automatic flute laminator for paperboard and corrugated board lamination.',
    },
    {
      name: 'Automatic Window Patching Machine',
      slug: 'automatic-window-patching-machine',
      categorySlug: 'window-patching',
      description: 'Automatic Window Patching Machine can be applied for lamination of cardboard to cardboard, cardboard to corrugation paperboard. Designed with auto suction feeding system for both top linerboards and bottom corrugated boards. Ideal choice for producing high end packaging boxes.',
      shortDescription: 'Automatic window patching machine for high-end packaging boxes.',
      specs: [
        { key: 'Warranty', value: '1 Year' },
        { key: 'Delivery Time', value: '40 to 45 Days' },
        { key: 'Max. Paper Size', value: '1500x1105mm' },
        { key: 'Min. Paper Size', value: '500x420mm' },
        { key: 'Max. Cutting Size', value: '1480x1090mm' },
        { key: 'Max. Pressure', value: '350 Tons' },
        { key: 'Sheet Thickness', value: 'Cardboard 250-2500g/m2, Corrugated Board < 8mm' },
        { key: 'Max. Cutting Speed', value: '5000 sheets/h' },
        { key: 'Die-Cutting Precision', value: '±0.18mm' },
        { key: 'Total Power', value: '20 KW' },
        { key: 'Weight', value: '20 Tons' },
      ],
      media: [{ type: 'image', url: '/images/product/Automatic-Window-Patching-Machine.png', alt: 'Automatic Window Patching Machine', sortOrder: 1 }],
      isActive: true,
      isFeatured: true,
      seoTitle: 'Automatic Window Patching Machine | Bark Technologies',
      seoDescription: 'Automatic window patching machine with auto suction feeding for high-end packaging.',
    },
    {
      name: 'RS-4 Rotary Printer',
      slug: 'RS-4-rottery-printer-machine',
      categorySlug: 'printing',
      description: 'RS-4 Rotary Printer can be applied for lamination of cardboard to cardboard, cardboard to corrugation paperboard. Designed with auto suction feeding system for both top linerboards and bottom corrugated boards. Features electric adjustment system for flute. Ideal for high-end packaging boxes.',
      shortDescription: 'RS-4 rotary printer with auto suction feeding for high-end packaging.',
      specs: [
        { key: 'Model', value: 'CH-1450*2600' },
        { key: 'Warranty', value: '1 Year' },
        { key: 'Delivery Time', value: '10 to 15 Days' },
        { key: 'Design Speed', value: '80 Piece/min' },
        { key: 'Max. feeding paper size', value: '1450x2500mm' },
        { key: 'Min. feeding paper size', value: '350mm' },
        { key: 'Max. printing size', value: '1400x2400mm' },
        { key: 'Printing precision', value: '±0.5mm' },
        { key: 'Standard plate thickness', value: '7.2mm' },
        { key: 'Printing paperboard thickness', value: '3-11mm' },
        { key: 'Total Power', value: '7 Kw' },
        { key: 'Electric adjustment System', value: 'System Flute' },
      ],
      media: [{ type: 'image', url: '/images/product/rottery-printer-RS-4.jpeg', alt: 'RS-4 Rotary Printer', sortOrder: 1 }],
      isActive: true,
      isFeatured: true,
      seoTitle: 'RS-4 Rotary Printer | Bark Technologies',
      seoDescription: 'RS-4 rotary printer with 80 piece/min speed for high-end packaging boxes.',
    },
    {
      name: 'NC Cutter Machine',
      slug: 'nc-cutter-machine',
      categorySlug: 'cutting',
      description: 'NC Cutter Machine — a revolutionary addition to precision cutting and shaping in the manufacturing world. Combines numerical control with cutting-edge technology. Intuitive interface ensures accurate and intricate cuts on a variety of materials. Built for reliability and durability with consistent, high-quality results even in demanding production environments.',
      shortDescription: 'Numerical-control precision cutting machine for accurate, intricate cuts.',
      specs: [
        { key: 'Model', value: 'KZ-YH1' },
        { key: 'Warranty', value: '1 Year' },
        { key: 'Delivery Time', value: '10 to 15 Days' },
        { key: 'Crease Matrix Specification', value: '0.3-3MM' },
        { key: 'Speed', value: '1-50m' },
        { key: 'Voltage', value: '220v 50HZ' },
        { key: 'Overall Weight', value: '40KG' },
        { key: 'Dimension', value: '45*31*45CM' },
      ],
      media: [{ type: 'image', url: '/images/product/nc-cutter-machine.jpeg', alt: 'NC Cutter Machine', sortOrder: 1 }],
      isActive: true,
      isFeatured: false,
      seoTitle: 'NC Cutter Machine | Bark Technologies',
      seoDescription: 'Numerical-control precision cutting machine for accurate, intricate cuts.',
    },
    {
      name: 'Single Facer Machine',
      slug: 'single-facer-machine',
      categorySlug: 'corrugating',
      description: 'Single Facer Machine — the cornerstone of corrugated cardboard production. Transforms paper into corrugated sheets essential for packaging strength and versatility. With precision engineering and automation, guarantees consistent, high-speed production while reducing labor costs. Crafted for durability and long-term reliability in demanding production environments.',
      shortDescription: 'Cornerstone machine for corrugated cardboard production with high-speed automation.',
      specs: [
        { key: 'Warranty', value: '1 Year' },
        { key: 'Delivery Time', value: '10 to 15 Days' },
        { key: 'Production Type', value: 'Corrugated cardboard' },
        { key: 'Operation', value: 'Automated' },
      ],
      media: [{ type: 'image', url: '/images/product/single-facer-machine.jpeg', alt: 'Single Facer Machine', sortOrder: 1 }],
      isActive: true,
      isFeatured: false,
      seoTitle: 'Single Facer Machine | Bark Technologies',
      seoDescription: 'Cornerstone machine for corrugated cardboard production with high-speed automation.',
    },
    {
      name: 'Electric Mill Roll Stand',
      slug: 'electric-mill-roll-stand-machine',
      categorySlug: 'material-handling',
      description: 'Electric Mill Roll Stand Machine — high-performance addition for unrolling and supporting paper rolls in various applications. Electric operation ensures effortless control, optimizing workflow. Crafted with durability for reliable performance over time. Suitable for packaging, printing, and other industries.',
      shortDescription: 'Electric mill roll stand for efficient paper roll handling.',
      specs: [
        { key: 'Warranty', value: '1 Year' },
        { key: 'Delivery Time', value: '10 to 15 Days' },
        { key: 'Operation', value: 'Electric' },
        { key: 'Use Case', value: 'Paper roll unrolling and support' },
      ],
      media: [{ type: 'image', url: '/images/product/Electric-Mill-Roll-Stand.jpeg', alt: 'Electric Mill Roll Stand', sortOrder: 1 }],
      isActive: true,
      isFeatured: false,
      seoTitle: 'Electric Mill Roll Stand | Bark Technologies',
      seoDescription: 'Electric mill roll stand for efficient paper roll handling in packaging and printing.',
    },
    {
      name: 'Auto Crease Matrix Cutter Machine',
      slug: 'auto-crease-matrix-cutter-machine',
      categorySlug: 'creasing-matrix',
      description: 'KZ-YH1 Auto Crease Matrix Cutter Machine — cutting-edge solution for precision and efficiency in creasing and cutting operations. Crease matrix specification 0.3 to 3mm ensures flawless creases. Variable speed 1-50m per minute enhances productivity. Operating at 220V/50HZ with lightweight 40KG and compact dimensions 45*31*45CM.',
      shortDescription: 'Precision creasing and cutting solution with 0.3-3mm crease matrix spec.',
      specs: [
        { key: 'Model', value: 'KZ-YH1' },
        { key: 'Warranty', value: '1 Year' },
        { key: 'Delivery Time', value: '10 to 15 Days' },
        { key: 'Crease Matrix Specification', value: '0.3-3MM' },
        { key: 'Speed', value: '1-50m' },
        { key: 'Voltage', value: '220v 50HZ' },
        { key: 'Overall Weight', value: '40KG' },
        { key: 'Dimension', value: '45*31*45CM' },
      ],
      media: [{ type: 'image', url: '/images/products/auto-crease-matrix-cutter-machine.jpg', alt: 'Auto Crease Matrix Cutter Machine', sortOrder: 1 }],
      isActive: true,
      isFeatured: false,
      seoTitle: 'Auto Crease Matrix Cutter Machine | Bark Technologies',
      seoDescription: 'Precision creasing and cutting solution with 0.3-3mm crease matrix spec.',
    },
    {
      name: 'Semi Automatic Stitching Machine',
      slug: 'semi-automatic-stitching-machine',
      categorySlug: 'stitching',
      description: 'Semi-Automatic Stitching Machine — the epitome of binding efficiency and precision. Merges automation with user control for crafting booklets, brochures, and magazines with consistent, professional stitching. Intuitive controls boost productivity while preserving craftsmanship. Two model variants available (TYS-1600 / TYS-2000).',
      shortDescription: 'Semi-automatic stitching machine for booklets, brochures, and magazines.',
      specs: [
        { key: 'Model', value: 'TYS-1600 | TYS-2000' },
        { key: 'Warranty', value: '1 Year' },
        { key: 'Delivery Time', value: '10 to 15 Days' },
        { key: 'Max. Sheet size', value: '3200mm | 4000mm' },
        { key: 'Min. Sheet size', value: '1060mm | 1060mm' },
        { key: 'Max. Paper Length Size, A Part', value: '1450mm | 1850mm' },
        { key: 'Min. Paper Length Size, A Part', value: '350mm | 350mm' },
        { key: 'Max. Paper Width size, B part', value: '800mm | 1000mm' },
        { key: 'Pitch of Nail', value: '30-100mm' },
        { key: 'Pitch Number', value: '2-99 Nails' },
        { key: 'Max. Machine speed', value: '600 Nail/Min' },
        { key: 'Power', value: '9 KW' },
        { key: 'Sheet thickness', value: 'A-E Corrugated board, 5 layer' },
        { key: 'Total Weight', value: '3500 KG | 3700 KG' },
        { key: 'Overall Dimension', value: '2700x2600x1600mm | 3100x2600x1600mm' },
      ],
      media: [{ type: 'image', url: '/images/products/semi-automatic-stitching-machine.png', alt: 'Semi Automatic Stitching Machine', sortOrder: 1 }],
      isActive: true,
      isFeatured: false,
      seoTitle: 'Semi Automatic Stitching Machine | Bark Technologies',
      seoDescription: 'Semi-automatic stitching machine for booklets, brochures, and magazines.',
    },
    {
      name: 'Automatic Folder Gluer Machine',
      slug: 'automatic-folder-gluer-machine',
      categorySlug: 'folder-gluing',
      description: 'Automatic Folder Gluer Machine for high-speed folding and gluing of corrugated boxes. Designed for efficient production of cartons and boxes with precision folding and consistent glue application.',
      shortDescription: 'Automatic folder gluer for high-speed corrugated box production.',
      specs: [
        { key: 'Warranty', value: '1 Year' },
        { key: 'Price', value: 'On Request*' },
        { key: 'Delivery Time', value: 'On Request' },
      ],
      media: [{ type: 'image', url: '/images/products/Automatic-folder-gluer.png', alt: 'Automatic Folder Gluer Machine', sortOrder: 1 }],
      isActive: true,
      isFeatured: false,
      seoTitle: 'Automatic Folder Gluer Machine | Bark Technologies',
      seoDescription: 'Automatic folder gluer machine for high-speed corrugated box folding and gluing.',
    },
    {
      name: 'Semi Automatic Folder Gluer Machine',
      slug: 'semi-automatic-folder-gluer-machine',
      categorySlug: 'folder-gluing',
      description: 'Semi Automatic Folder Gluer Machine for folding and gluing of corrugated boxes with operator-assisted operation. Reliable performance for medium-volume box production.',
      shortDescription: 'Semi-automatic folder gluer for medium-volume box production.',
      specs: [
        { key: 'Warranty', value: '1 Year' },
        { key: 'Price', value: 'On Request*' },
        { key: 'Delivery Time', value: 'On Request' },
      ],
      media: [{ type: 'image', url: '/images/products/Semi-automatic-folder-gluer-machine.png', alt: 'Semi Automatic Folder Gluer Machine', sortOrder: 1 }],
      isActive: true,
      isFeatured: false,
      seoTitle: 'Semi Automatic Folder Gluer Machine | Bark Technologies',
      seoDescription: 'Semi-automatic folder gluer machine for corrugated box folding and gluing.',
    },
    {
      name: 'Manual 3/5/7 Flyer Pasting Machine',
      slug: 'manual-flyer-pasting-machine',
      categorySlug: 'pasting',
      description: 'Manual 3/5/7 Flyer Pasting Machine for pasting corrugated boards and sheets. Available in 3, 5, and 7 flyer configurations for different production capacities.',
      shortDescription: 'Manual flyer pasting machine for corrugated board pasting.',
      specs: [
        { key: 'Warranty', value: '1 Year' },
        { key: 'Price', value: 'On Request*' },
        { key: 'Delivery Time', value: 'On Request' },
        { key: 'Configuration', value: '3/5/7 Flyers' },
      ],
      media: [],
      isActive: true,
      isFeatured: false,
      seoTitle: 'Manual 3/5/7 Flyer Pasting Machine | Bark Technologies',
      seoDescription: 'Manual flyer pasting machine for corrugated board pasting.',
    },
    {
      name: 'Cardboard Box Sheet Pasting Machine',
      slug: 'cardboard-box-sheet-pasting-machine',
      categorySlug: 'pasting',
      description: 'Cardboard Box Sheet Pasting Machine for pasting cardboard sheets and boxes. Reliable and efficient pasting solution for packaging industry.',
      shortDescription: 'Cardboard box sheet pasting machine for packaging industry.',
      specs: [
        { key: 'Warranty', value: '1 Year' },
        { key: 'Price', value: 'On Request*' },
        { key: 'Delivery Time', value: 'On Request' },
      ],
      media: [],
      isActive: true,
      isFeatured: false,
      seoTitle: 'Cardboard Box Sheet Pasting Machine | Bark Technologies',
      seoDescription: 'Cardboard box sheet pasting machine for packaging industry.',
    },
    {
      name: 'Automatic Film Lamination Machine',
      slug: 'automatic-film-lamination-machine',
      categorySlug: 'laminating',
      description: 'Automatic Film Lamination Machine for applying protective film lamination on printed sheets. Designed for high-quality lamination with precise temperature and speed control.',
      shortDescription: 'Automatic film lamination machine for printed sheets.',
      specs: [
        { key: 'Warranty', value: '1 Year' },
        { key: 'Price', value: 'On Request*' },
        { key: 'Delivery Time', value: 'On Request' },
      ],
      media: [],
      isActive: true,
      isFeatured: false,
      seoTitle: 'Automatic Film Lamination Machine | Bark Technologies',
      seoDescription: 'Automatic film lamination machine for printed sheets.',
    },
  ],

  faqs: [
    { question: 'What products does Bark Technologies manufacture?', answer: 'Bark Technologies manufactures a wide range of packaging machinery including: Automatic Die Cutting & Creasing Machines, High-Speed Automatic Die Cutting & Creasing Machines, Semi-Automatic Die Cutting & Creasing Machines, Automatic Flute Laminator Machines, Automatic Window Patching Machines, High-Speed Automatic Flute Laminator Machines, Semi-Automatic Flute Laminator Machines, Semi-Automatic Stitching Machines, Rotary Printer (RS-4) Machines, Electric Mill Roll Stands, NC Cutter Machines, Single Facer Machines, Auto Crease Matrix Cutter, Automatic & Semi-Automatic Folder Gluer Machines, Manual 3/5/7 Flyer Pasting Machines, Cardboard Box Sheet Pasting Machines, and Automatic Film Lamination Machines.', isActive: true, order: 1 },
    { question: 'Where is Bark Technologies located?', answer: 'Our head office is at SF-03, Local Shopping Complex, Shushat Aquapolis, Ghaziabad - 201009, Uttar Pradesh, India. We also have a spare branch office in Noida (F-41, 1st Floor, Sec 9, Noida 201301, UP, India) and service accommodations in Ahmedabad & Vadodara, Gujarat.', isActive: true, order: 2 },
    { question: 'What is the warranty period for your machines?', answer: 'All our machines come with a 1-year warranty covering manufacturing defects.', isActive: true, order: 3 },
    { question: 'What is the typical delivery time?', answer: 'Delivery time varies by product: die cutting machines take 40-60 days, flute laminators 35-40 days, and smaller machines like NC cutters and rotary printers take 10-15 days. Contact us for product-specific delivery times.', isActive: true, order: 4 },
    { question: 'Do you provide installation and after-sales support?', answer: 'Yes, we provide complete installation, regular maintenance, and machine repair services across all cities we operate in. Our skilled and experienced team ensures smooth installation, regular maintenance, and reliable after-sales support, so your operations stay hassle-free.', isActive: true, order: 5 },
    { question: 'In which cities have you installed machines?', answer: 'We have successfully installed over 100+ machines in major cities including Ahmedabad, Noida, Pune, Meerut, Agra, Baroda, Thane, Chennai, Bengaluru, Ghaziabad, and more.', isActive: true, order: 6 },
    { question: 'How can I request a quote?', answer: 'You can request a quote by filling out the contact form on our Contact page, calling us at +91 8810597980, or emailing info@barktechnologies.in. For sales queries, email sales1@barktechnologies.in. For service queries, email service@barktechnologies.in. You can also use our AI chat assistant.', isActive: true, order: 7 },
    { question: 'What is the UDYAM registration number?', answer: 'Our UDYAM registration number is UDYAM-UP-28-0004163.', isActive: true, order: 8 },
    { question: 'Why should I choose Bark Technologies?', answer: 'We provide 100% client satisfaction with best quality products and guaranteed on-time delivery. We offer fast response, quality work, certified industry specialists, and a 100% secure & transparent procedure. We are a distinguished firm engaged in manufacturing, wholesale, and supply of packaging machinery.', isActive: true, order: 9 },
    { question: 'Since when has Bark Technologies been operating?', answer: 'We have been providing high quality service in India as well as neighbouring countries with trust since 2019.', isActive: true, order: 10 },
  ],

  offices: [
    {
      name: 'Head Office',
      location: 'Ghaziabad',
      address: 'SF-03, Local Shopping Complex, Shushat Aquapolis, Ghaziabad - 201009, Uttar Pradesh, India',
      phone: '+91 8810597980',
      email: 'info@barktechnologies.in',
      serviceEmail: 'service@barktechnologies.in',
      salesEmail: 'sales1@barktechnologies.in',
      businessHours: 'Mon - Fri: 10:00 - 18:00',
      isActive: true,
      sortOrder: 1,
    },
    {
      name: 'Spare Branch Office',
      location: 'Noida',
      address: 'F-41, 1st Floor, Sec 9, Noida 201301, UP, India',
      phone: '+91 9266244587',
      email: 'info@barktechnologies.in',
      isActive: true,
      sortOrder: 2,
    },
    {
      name: 'Service Accommodation',
      location: 'Ahmedabad & Vadodara',
      address: 'Ahmedabad & Vadodara, Gujarat, India',
      phone: '+91 9266244587',
      email: 'info@barktechnologies.in',
      isActive: true,
      sortOrder: 3,
    },
  ],

  newsArticles: [
    {
      title: 'Sheet Cutter/NC Cutter Machine — Upcoming to India',
      slug: 'sheet-cutter-nc-cutter-upcoming-india',
      summary: 'Our latest consignment is being loaded into containers, featuring a high-performance Sheet Cutter/NC Cutter Machine, en route from China to India! This cutting-edge machine is a game-changer in precision cutting.',
      content: 'Big News! Our latest consignment is being loaded into containers, featuring a high-performance Sheet Cutter/NC Cutter Machine, is en route from China to India! This cutting-edge machine is a game-changer in precision cutting, designed to elevate your production processes.',
      imageUrl: '/images/news-images/16.png',
      publishedAt: new Date('2023-09-16'),
      isActive: true,
      isPublished: true,
    },
    {
      title: 'Single Color Flexo Machine — Upcoming to India',
      slug: 'single-color-flexo-upcoming-india',
      summary: 'Our latest consignment featuring a high-performance Single Color Flexo Machine is en route from China to India!',
      content: 'Big News! Our latest consignment is being loaded into containers, featuring a high-performance Single Color Flexo Machine, is en route from China to India! This cutting-edge machine is a game-changer in precision printing, designed to elevate your production processes.',
      imageUrl: '/images/news-images/166.png',
      publishedAt: new Date('2023-09-16'),
      isActive: true,
      isPublished: true,
    },
    {
      title: 'Semi Automatic Die Machine — Upcoming to India',
      slug: 'semi-automatic-die-machine-upcoming-india',
      summary: 'Our latest consignment featuring a Semi Automatic Die Machine is en route to India!',
      content: 'Big News! Our latest consignment is being loaded into containers, featuring a high-performance Semi Automatic Die Machine, is en route from China to India! This cutting-edge machine is a game-changer in die cutting, designed to elevate your production processes.',
      videoUrl: '/images/news-images/29.mp4',
      publishedAt: new Date('2023-08-29'),
      isActive: true,
      isPublished: true,
    },
    {
      title: 'Automatic Flute Laminator Machine — Successful installation in Gujarat',
      slug: 'automatic-flute-laminator-installation-gujarat',
      summary: 'Successful installation of our new Automatic Flute Laminator Machine in Morbi, Gujarat. Experience the cutting-edge technology that elevates packaging solutions to new heights!',
      content: 'Successful installation of our new Automatic Flute Laminator Machine in Morbi, Gujarat. Experience the cutting-edge technology that elevates packaging solutions to new heights!',
      imageUrl: '/images/news-images/gujrat.png',
      publishedAt: new Date('2023-08-08'),
      isActive: true,
      isPublished: true,
    },
  ],

  installations: [
    {
      title: 'Automatic Flute Laminator Installation in Morbi, Gujarat',
      description: 'Successful installation of our Automatic Flute Laminator Machine at a leading packaging manufacturer in Morbi, Gujarat. The machine is now operational and producing high-quality laminated corrugated boards.',
      location: 'Morbi, Gujarat, India',
      clientName: 'Packaging Manufacturer (Confidential)',
      installedOn: new Date('2023-08-08'),
      coverImageUrl: '/images/news-images/gujrat.png',
      productId: null,
      sortOrder: 1,
      isActive: true,
    },
    {
      title: 'Die Cutting Machine Installation in Ahmedabad',
      description: 'Installation of Automatic Die Cutting And Creasing Machine at a corrugated box manufacturing facility in Ahmedabad. The machine handles high-volume die cutting with precision.',
      location: 'Ahmedabad, Gujarat, India',
      clientName: 'Corrugated Box Manufacturer (Confidential)',
      installedOn: new Date('2023-06-15'),
      coverImageUrl: '/images/news-images/16.png',
      productId: null,
      sortOrder: 2,
      isActive: true,
    },
    {
      title: 'NC Cutter Machine Installation in Noida',
      description: 'Installation of NC Cutter Machine at a packaging facility in Noida. The machine provides precision cutting for corrugated sheets.',
      location: 'Noida, UP, India',
      clientName: 'Packaging Facility (Confidential)',
      installedOn: new Date('2023-05-20'),
      coverImageUrl: '/images/news-images/166.png',
      productId: null,
      sortOrder: 3,
      isActive: true,
    },
  ],

  blogPosts: [
    {
      title: 'How to Choose the Right Die Cutting Machine for Your Packaging Business',
      slug: 'choose-right-die-cutting-machine',
      excerpt: 'A comprehensive guide to selecting the perfect die cutting machine for your packaging business, covering key specifications, capacity, and budget considerations.',
      content: 'Die cutting machines are essential for packaging manufacturers. This guide covers the key factors to consider when choosing a die cutting machine: sheet size, cutting speed, pressure capacity, precision requirements, and automation level. We also discuss the differences between automatic, semi-automatic, and high-speed variants.',
      imageUrl: '/images/product/automatic-die-cutting-and-creasing.png',
      tags: ['die-cutting', 'packaging', 'machinery', 'buying-guide'],
      published: true,
      reviewStatus: 'approved',
      publishedAt: new Date('2023-09-01'),
    },
    {
      title: 'Flute Lamination: Benefits and Best Practices',
      slug: 'flute-lamination-benefits-best-practices',
      excerpt: 'Learn about the benefits of flute lamination and best practices for achieving optimal results with your flute laminator machine.',
      content: 'Flute lamination is a critical process in corrugated packaging production. This article covers the benefits of automatic flute lamination, best practices for machine operation, maintenance tips, and how to achieve maximum productivity with your flute laminator.',
      imageUrl: '/images/product/high-speed-automatic-flute-laminator.png',
      tags: ['laminating', 'corrugated', 'best-practices'],
      published: true,
      reviewStatus: 'approved',
      publishedAt: new Date('2023-08-15'),
    },
    {
      title: 'Post-Press Equipment: Trends in 2024',
      slug: 'post-press-equipment-trends-2024',
      excerpt: 'Explore the latest trends in post-press equipment and how they are shaping the packaging industry.',
      content: 'The post-press equipment industry is evolving rapidly with automation, digital integration, and sustainability becoming key trends. This article explores what packaging manufacturers should expect in the coming year.',
      imageUrl: '/images/matrix/main-banner.png',
      tags: ['trends', 'industry', 'automation'],
      published: false,
      reviewStatus: 'draft',
    },
  ],

  caseStudies: [
    {
      title: 'High-Speed Die Cutting Solution for Large-Scale Box Manufacturer',
      slug: 'high-speed-die-cutting-case-study',
      clientName: 'Large-Scale Box Manufacturer',
      location: 'Pune, Maharashtra, India',
      industry: 'Corrugated Packaging',
      summary: 'How our High Speed Automatic Die Cutting & Creasing Machine helped a large-scale box manufacturer increase production capacity by 40% while maintaining precision.',
      content: 'A large-scale corrugated box manufacturer in Pune was facing production bottlenecks with their existing die cutting equipment. After installing our High Speed Automatic Die Cutting & Creasing Machine (MY-1050FAST), they achieved cutting speeds of up to 10,000 sheets/hour with ±0.1mm precision. The result was a 40% increase in production capacity and significant reduction in waste.',
      imageUrl: '/images/product/High-Speed-Automatic-Die-Cutting-and-creasing-machine.png',
      published: true,
      reviewStatus: 'approved',
      publishedAt: new Date('2023-07-15'),
    },
    {
      title: 'Automatic Flute Laminator Transforms Packaging Production in Gujarat',
      slug: 'flute-laminator-gujarat-case-study',
      clientName: 'Packaging Manufacturer',
      location: 'Morbi, Gujarat, India',
      industry: 'Corrugated Packaging',
      summary: 'A Morbi-based packaging manufacturer improved lamination efficiency by 60% after installing our Automatic Flute Laminator Machine.',
      content: 'A packaging manufacturer in Morbi, Gujarat was struggling with manual lamination processes that were slow and inconsistent. After installing our Automatic Flute Laminator Machine (FMZ-1450H), they achieved speeds of 9,000 pcs/h with ±1mm precision. The auto suction feeding system eliminated manual handling, improving both speed and quality.',
      imageUrl: '/images/product/high-speed-automatic-flute-laminator.png',
      published: true,
      reviewStatus: 'approved',
      publishedAt: new Date('2023-08-10'),
    },
  ],
};
