#!/usr/bin/env python3
"""Test: Send invoice email with the REAL PDF (generated by WeasyPrint).

Flow:
  1. POST invoice data to the Python agent's /invoice/generate-pdf endpoint
  2. Agent generates the real PDF using WeasyPrint + Jinja2 invoice.html template
  3. We render the email HTML template with the same invoice data
  4. Send the email with the real PDF as attachment via Brevo
"""

import asyncio
import base64
import os
import re
import sys
import httpx

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.mcp.email_mcp import send_email

TO_EMAIL = "hg280175@gmail.com"
AGENT_URL = os.getenv("AGENT_URL", "http://localhost:8000")

# -- Real invoice data (matches what the admin panel generates) --

INVOICE_DATA = {
    "company_name": "Bark Technology",
    "company_address": "SF-03, Local Shopping Complex, Shushant Aquapolis, Ghaziabad UP 201009",
    "company_gstin": "09AAWFB1759R1ZC",
    "company_logo_url": "https://barktechnologies.in/images/logo/logo.png",
    "invoice_no": "BARK-INV-2026-0042",
    "invoice_date": "25 July 2026",
    "due_date": "24 August 2026",
    "place_of_supply": "Uttar Pradesh (09)",
    "state_code": "09",
    "buyer_name": "Gupta Enterprises",
    "buyer_address": "45, Industrial Estate, Kanpur, UP 208001",
    "buyer_gstin": "09DEFGH5678I1Z8",
    "ship_to_name": "Gupta Enterprises - Warehouse",
    "ship_to_address": "78, Sector 62, Noida, UP 201301",
    "subtotal": "1,85,000.00",
    "cgst": "16,650.00",
    "sgst": "16,650.00",
    "igst": "",
    "round_off": "",
    "grand_total": "2,18,300.00",
    "amount_in_words": "Rupees Two Lakh Eighteen Thousand Three Hundred Only",
    "bank_account_name": "BARK TECHNOLOGIES",
    "bank_account_no": "157905003103",
    "bank_ifsc": "ICIC0001579",
    "bank_name": "ICICI BANK LTD - Noida 132",
    "authorized_signatory": "Rajesh Kumar",
    "company_seal_note": "This is a computer-generated invoice.",
    "pdf_download_url": f"https://barktechnologies.in/invoices/BARK-INV-2026-0042.pdf",
    "support_email": "support@barktechnologies.in",
    "support_phone": "+91 98765 43210",
}

ITEM_ROWS = [
    {"sno": "1", "description": "Automatic Die Cutting & Creasing Machine 1100mm", "hsn_code": "8462", "qty": "1", "unit": "NOS", "rate": "85,000.00", "gst_percent": "18", "amount": "1,00,300.00"},
    {"sno": "2", "description": "Servo Based Automatic Capping Machine", "hsn_code": "8462", "qty": "2", "unit": "NOS", "rate": "35,000.00", "gst_percent": "18", "amount": "82,600.00"},
    {"sno": "3", "description": "Installation & Commissioning Charges", "hsn_code": "9983", "qty": "1", "unit": "NOS", "rate": "10,000.00", "gst_percent": "18", "amount": "11,800.00"},
    {"sno": "4", "description": "Spare Parts Kit (Seals, Bearings, O-Rings)", "hsn_code": "8462", "qty": "1", "unit": "SET", "rate": "8,500.00", "gst_percent": "18", "amount": "10,030.00"},
]

TERMS = [
    "Payment is due within 30 days of invoice date.",
    "Interest at 1.5% per month will be charged on overdue amounts.",
    "Goods once sold will not be taken back or exchanged.",
    "E. & O.E. (Errors and Omissions Excepted).",
    "Subject to Noida jurisdiction.",
]


def load_template(name: str) -> str:
    tpl_path = os.path.join(os.path.dirname(__file__), "templates", name)
    with open(tpl_path, "r") as f:
        return f.read()


def render_invoice_template(html: str) -> str:
    """Render the email HTML template by replacing loops and placeholders."""

    # -- 1. Replace {{#each item_rows}} ... {{/each}} --
    item_pattern = re.compile(
        r"<!-- \{\{#each item_rows\}\} -->.*?<!-- \{\{/each\}\} -->", re.DOTALL
    )
    item_match = item_pattern.search(html)
    if item_match:
        loop_content = item_match.group(0)
        single_row = re.search(r"(<tr>.*?</tr>)", loop_content, re.DOTALL)
        if single_row:
            row_template = single_row.group(1)
            rows_html = ""
            for i, item in enumerate(ITEM_ROWS):
                bg = "#ffffff" if i % 2 == 0 else "#fafafa"
                row = row_template
                for key, val in item.items():
                    row = row.replace("{{this." + key + "}}", str(val))
                row = row.replace("{{#if @odd}}", bg if i % 2 != 0 else "")
                row = row.replace("{{else}}", "")
                row = row.replace("{{/if}}", "")
                rows_html += "\n                  " + row
            html = html[:item_match.start()] + rows_html + "\n                  " + html[item_match.end():]

    # -- 2. Replace {{#each terms}} ... {{/each}} --
    term_pattern = re.compile(
        r"<!-- \{\{#each terms\}\} -->.*?<!-- \{\{/each\}\} -->", re.DOTALL
    )
    term_match = term_pattern.search(html)
    if term_match:
        loop_content = term_match.group(0)
        single_row = re.search(r"(<tr>.*?</tr>)", loop_content, re.DOTALL)
        if single_row:
            row_template = single_row.group(1)
            terms_html = ""
            for i, term_text in enumerate(TERMS, 1):
                row = row_template
                row = row.replace("{{this.number}}", str(i))
                row = row.replace("{{this.text}}", term_text)
                terms_html += "\n                  " + row
            html = html[:term_match.start()] + terms_html + "\n                  " + html[term_match.end():]

    # -- 3. Replace all remaining {{variable}} placeholders --
    for key, val in INVOICE_DATA.items():
        html = html.replace("{{" + key + "}}", str(val))

    # -- 4. Clean any remaining Handlebars comments/syntax --
    html = re.sub(r"<!-- \{\{#if \w+\}\} -->", "", html)
    html = re.sub(r"<!-- \{\{/if\}\} -->", "", html)
    html = re.sub(r"<!-- \{\{else\}\} -->", "", html)
    html = re.sub(r"\{\{#if\s+\w+\}\}", "", html)
    html = re.sub(r"\{\{/if\}\}", "", html)
    html = re.sub(r"\{\{else\}\}", "", html)
    html = re.sub(r"\{\{#each\s+\w+\}\}", "", html)
    html = re.sub(r"\{\{/each\}\}", "", html)

    return html


async def generate_real_pdf() -> bytes:
    """Call the Python agent's /invoice/generate-pdf to get the REAL WeasyPrint PDF."""

    # Build the payload that the agent's GeneratePDFRequest expects
    payload = {
        "invoice_number": INVOICE_DATA["invoice_no"],
        "customer_name": INVOICE_DATA["buyer_name"],
        "customer_company": INVOICE_DATA["buyer_name"],
        "customer_address": INVOICE_DATA["buyer_address"],
        "customer_gst": INVOICE_DATA["buyer_gstin"],
        "ship_to_address": INVOICE_DATA["ship_to_address"],
        "mode_of_delivery": "BY TRANSPORT",
        "items": [
            {"description": item["description"], "hsn_code": item["hsn_code"],
             "quantity": int(item["qty"]), "unit_price": float(item["rate"].replace(",", "")),
             "gst_rate": float(item["gst_percent"])}
            for item in ITEM_ROWS
        ],
        "gst_rate": 18.0,
        "invoice_date": "2026-07-25",
        "bank_name": INVOICE_DATA["bank_account_name"],
        "bank_bank": INVOICE_DATA["bank_name"].split(" - ")[0],
        "bank_account_no": INVOICE_DATA["bank_account_no"],
        "bank_ifsc": INVOICE_DATA["bank_ifsc"],
    }

    print(f"\n--- Generating REAL PDF via agent at {AGENT_URL}/invoice/generate-pdf ---")

    try:
        async with httpx.AsyncClient(timeout=60) as client:
            resp = await client.post(
                f"{AGENT_URL}/invoice/generate-pdf",
                json=payload,
                headers={"Content-Type": "application/json"},
            )

            if resp.status_code == 200:
                content_type = resp.headers.get("content-type", "")
                if "application/pdf" in content_type:
                    pdf_bytes = resp.content
                    print(f"  PDF generated: {len(pdf_bytes)} bytes")
                    return pdf_bytes
                else:
                    # Might have returned JSON with file path
                    data = resp.json()
                    print(f"  Agent returned non-PDF: {data}")
                    # Try to read the file if it's a file path
                    if "detail" in data:
                        print(f"  Error: {data['detail']}")
            else:
                print(f"  Agent returned HTTP {resp.status_code}: {resp.text[:500]}")
    except httpx.ConnectError:
        print(f"  ERROR: Cannot connect to agent at {AGENT_URL}")
        print("  Make sure the agent is running: uvicorn app.main:app --reload --port 8000")
    except Exception as e:
        print(f"  ERROR generating PDF: {e}")

    return None


async def send_invoice_email():
    """Send invoice email with real PDF attachment."""

    # Step 1: Generate the REAL PDF from the agent
    pdf_bytes = await generate_real_pdf()

    if pdf_bytes is None:
        print("\n  PDF generation failed. Cannot send email without PDF.")
        return {"success": False, "error": "PDF generation failed"}

    # Step 2: Render the email HTML template
    template = load_template("invoice_email.html")
    rendered_html = render_invoice_template(template)

    print(f"\n--- Template Rendering Check ---")
    print(f"  buyer_name: {'Gupta Enterprises' in rendered_html}")
    print(f"  invoice_no: {'BARK-INV-2026-0042' in rendered_html}")
    print(f"  Items: {'Automatic Die Cutting' in rendered_html}")
    print(f"  Terms: {'Payment is due within 30 days' in rendered_html}")

    # Step 3: Encode PDF as base64 for Brevo API
    pdf_b64 = base64.b64encode(pdf_bytes).decode("utf-8")

    attachments = [
        {
            "filename": f"Invoice_{INVOICE_DATA['invoice_no']}.pdf",
            "content": pdf_b64,
            "contentType": "application/pdf",
        }
    ]

    subject = f"Invoice {INVOICE_DATA['invoice_no']} -- {INVOICE_DATA['company_name']}"
    print(f"\n--- Sending Invoice Email ---")
    print(f"  To: {TO_EMAIL}")
    print(f"  Subject: {subject}")
    print(f"  PDF Size: {len(pdf_bytes):,} bytes (real WeasyPrint PDF)")

    result = await send_email(TO_EMAIL, subject, rendered_html, attachments=attachments)
    return result


async def main():
    print("=" * 60)
    print("  BARK TECHNOLOGY -- Invoice Email (REAL PDF Attachment)")
    print("=" * 60)

    r = await send_invoice_email()
    print(f"\nResult: {r}")


if __name__ == "__main__":
    asyncio.run(main())
